:toc:

= Jupyter Notebook VSCode Template

[%hardbreaks]
Jupyter NotebookをVSCode上で使うときのプロジェクトテンプレート。
※Windows向けに書いている。

== ■ テンプレートの使い方

=== ▼ 前準備（当該端末で一度だけ）
==== ◎ Pythonセットアップ

* Miniconda3 or Anaconda3 インストール
* `PATH` 設定
* `pip install pipenv` 実行
* 環境変数 `PIPENV_VENV_IN_PROJECT` に `true` を設定

==== ◎ VSCode拡張機能のインストール

* Python
* Pipenv Scripts

=== ▼ 本手順
. Github.com(https://github.com/new )で空の新規リポジトリを作る
. git cloneしてcdする +
`git clone https://github.com/isoittech/jupyter_vscode_template.git <<任意のプロジェクト名>>`
. GitリポジトリのRemote URLを変更する +
`git remote set-url origin https://github.com/xxxxxxxxxxxx/yyyyyyyyyy.git`
. Pipfile.lockから仮想環境の再現
+
```shell
$ pipenv sync
$ pipenv sync --dev    # 開発用パッケージ
$ pipenv shell         # pipenv install でパッケージ追加する等の前処理として必要
※$ exit                 # 仮想環境から抜ける
```
. `code .` を実行してVSCodeでプロジェクトを開く
. VSCodeで `Shift+Ctrl+P` -> `Python: インタープリターを選択` から `.venv/Scripts/python.exe` を選択する
. あとは普通に開発・commit・pushする

== ■ このテンプレを作る上でやったことの記録

=== ▼ Pythonセットアップ

* Minicondaインストール
* `PATH` 設定
* `pip install pipenv` 実行
* 環境変数 `PIPENV_VENV_IN_PROJECT` に `true` を設定

=== ▼ VSCode拡張機能のインストール

* Python
* Pipenv Scripts


=== ▼ Git

```shell
$ git init
```

=== ▼ Pythonのランタイム設定・環境作成

```shell
$ pipenv --python 3.X
$ pipenv shell
$ pipenv install \
    jupyter \
    pandas \
    matplotlib \
    seaborn \
    numpy==1.19.3
$ pipenv install --dev \
    pylint \
    ipython \
    ipykernel
```
[%hardbreaks]
※Pandas：データ解析ライブラリ
※Matplotlib：データ解析用グラフ描画ライブラリ
※seaborn：データ可視化ライブラリ
※numpy==1.19.3：1.19.4はバグ（https://tinyurl.com/y3dm3h86 )があり使えないための指定。


== ■ 任意の追加手順

=== ▼ Jupyter NotebookをPDF保存するための手順

==== ◎ 環境作成
. Pandocインストール +
https://pandoc.org/installing.html
. LaTeXレンダリングエンジン（XeLaTex）をインストール +
https://miktex.org/download
. VSCodeに拡張機能「vscode-pandoc」by Chris Chinchillaをインストール +
※本家（DougFinke）は開発が2016で止まっているため。

==== ◎ 実行
. NotebookのエクスポートメニューからPDFを選択。 +
※初回、パッケージをいくつもダウンロードさせられる。ダイアログ対応が面倒な場合は `Show always..` のチェックボックスをOFFにする。 +
※初回だからなのか、A4 PDF 16ページ分を出力するのに、10分くらいかかった。 +
　CPU：Core i7、 メモリ：16GB、 HDDはSSD。

== ■ メモ

=== ▼ 仮想環境関連の操作

```shell
$ # 仮想環境へ入る
$ pipenv shell # 抜けるときはexit
$ # 仮想環境のパスが知りたい場合
$ pipenv --venv
$ # 仮想環境を削除する
$ pipenv --rm
$ # パッケージインストール ※バージョン指定は「==バージョン」と指定する
$ pipenv install numpy==1.14
```

=== ▼ cloneした人が実行すること

```shell
$ # Pipfile.lockから環境の再現
$ pipenv sync
$ pipenv sync --dev    # 開発用パッケージ
```

=== ▼ プロンプトに仮想環境名を出すマジナイ
```shell
$ vi ~/.bashrc
-------
export PS1='${VIRTUAL_ENV:+($(basename `echo $VIRTUAL_ENV`))}[\u@\h \W]\$ '
-------
$ source ~/.bashrc
```

== ■ 参考

* https://qiita.com/y-tsutsu/items/54c10e0b2c6b565c887a[Pipenvを使ったPython開発まとめ
]